### ISSUE TITLE
install hangs for htop-1.0.3

### ISSUE THREAD

**Issue by Cojad** [lj2007331/lempstack#1]
./install.sh will not keep going after " make[1]: Leaving directory `/htop-1.0.3' "
I can hit ctrl+c to leave script but it was not finished.

I tried on bot Vultr CentOS 7 x64/CentOS 6 x64 but both hangs at same place.
I'm looking at log to find out why
## My options:

Please input SSH port(Default: 22):
Do you want to install Web server? [y/n]: y
Please select Nginx server:
        1. Install Nginx
Please input a number:(Default 1 press Enter) 1
Do you want to install Database? [y/n]: y
Please select a version of the Database:
        3. Install MariaDB-10.0
Please input a number:(Default 1 press Enter) 3
Please input the root password of database: test
Do you want to install PHP? [y/n]: y
Please select a version of the PHP:
        4. Install php-5.6
Please input a number:(Default 3 press Enter) 4
Do you want to install opcode cache of the PHP? [y/n]: n
Do you want to install ZendGuardLoader? [y/n]: n
Do you want to install ionCube? [y/n]: n
Do you want to install ImageMagick or GraphicsMagick? [y/n]: n
Do you want to install Pure-FTPd? [y/n]: y
Do you want to install phpMyAdmin? [y/n]: y
Do you want to install redis? [y/n]: n
Do you want to install memcached? [y/n]: n
Do you want to use jemalloc or tcmalloc optimize Database and Web server? [y/n]: y
Please select jemalloc or tcmalloc:
        1. jemalloc
Please input a number:(Default 1 press Enter) 1
Do you want to install HHVM? [y/n]: n
## Last few lines of script

```
mv -f .deps/htop-IncSet.Tpo .deps/htop-IncSet.Po
/bin/sh ./libtool --tag=CC   --mode=link gcc -pedantic -Wall -Wextra -std=c99 -rdynamic -D_XOPEN_SOURCE_EXTENDED -DSYSCONFDIR=\"/usr/local/etc\" -g -O2   -o htop  htop-AvailableMetersPanel.o htop-CategoriesPanel.o htop-CheckItem.o htop-ClockMeter.o htop-ColorsPanel.o htop-ColumnsPanel.o htop-CPUMeter.o htop-CRT.o htop-DisplayOptionsPanel.o htop-FunctionBar.o htop-Hashtable.o htop-Header.o htop-htop.o htop-ListItem.o htop-LoadAverageMeter.o htop-MemoryMeter.o htop-Meter.o htop-MetersPanel.o htop-Object.o htop-Panel.o htop-BatteryMeter.o htop-Process.o htop-ProcessList.o htop-RichString.o htop-ScreenManager.o htop-Settings.o htop-IOPriorityPanel.o htop-SignalsPanel.o htop-String.o htop-SwapMeter.o htop-TasksMeter.o htop-TraceScreen.o htop-UptimeMeter.o htop-UsersTable.o htop-Vector.o htop-AvailableColumnsPanel.o htop-AffinityPanel.o htop-HostnameMeter.o htop-OpenFilesScreen.o htop-Affinity.o htop-IOPriority.o htop-IncSet.o  -lncursesw -lm
libtool: link: gcc -pedantic -Wall -Wextra -std=c99 -rdynamic -D_XOPEN_SOURCE_EXTENDED -DSYSCONFDIR=\"/usr/local/etc\" -g -O2 -o htop htop-AvailableMetersPanel.o htop-CategoriesPanel.o htop-CheckItem.o htop-ClockMeter.o htop-ColorsPanel.o htop-ColumnsPanel.o htop-CPUMeter.o htop-CRT.o htop-DisplayOptionsPanel.o htop-FunctionBar.o htop-Hashtable.o htop-Header.o htop-htop.o htop-ListItem.o htop-LoadAverageMeter.o htop-MemoryMeter.o htop-Meter.o htop-MetersPanel.o htop-Object.o htop-Panel.o htop-BatteryMeter.o htop-Process.o htop-ProcessList.o htop-RichString.o htop-ScreenManager.o htop-Settings.o htop-IOPriorityPanel.o htop-SignalsPanel.o htop-String.o htop-SwapMeter.o htop-TasksMeter.o htop-TraceScreen.o htop-UptimeMeter.o htop-UsersTable.o htop-Vector.o htop-AvailableColumnsPanel.o htop-AffinityPanel.o htop-HostnameMeter.o htop-OpenFilesScreen.o htop-Affinity.o htop-IOPriority.o htop-IncSet.o  -lncursesw -lm
make[1]: Leaving directory `/htop-1.0.3'
make  install-am
make[1]: Entering directory `/htop-1.0.3'
make[2]: Entering directory `/htop-1.0.3'
test -z "/usr/local/bin" || /bin/mkdir -p "/usr/local/bin"
  /bin/sh ./libtool   --mode=install /bin/install -c htop '/usr/local/bin'
libtool: install: /bin/install -c htop /usr/local/bin/htop
test -z "/usr/local/share/applications" || /bin/mkdir -p "/usr/local/share/applications"
 /bin/install -c -m 644 htop.desktop '/usr/local/share/applications'
test -z "/usr/local/share/man/man1" || /bin/mkdir -p "/usr/local/share/man/man1"
 /bin/install -c -m 644 htop.1 '/usr/local/share/man/man1'
test -z "/usr/local/share/pixmaps" || /bin/mkdir -p "/usr/local/share/pixmaps"
 /bin/install -c -m 644 htop.png '/usr/local/share/pixmaps'
make[2]: Leaving directory `/htop-1.0.3'
make[1]: Leaving directory `/htop-1.0.3'
```

**Comment by Cojad** [comment]
I found the cause of this issue and solved the problem.
sourceforge has some mirror problem on ipv6 server. The one used by vultr vps to connect return 404 on libevent-2.0.22-stable.tag.gz. This issue is not always happen since it just an ipv6 sourceforge server mirror return 404. I fix the problem by change to path to Taiwan mirror. So the script can now able to finish that part without problem.

**Comment by oneinstack** [comment]
If you do not install `htop`, you can edit `include/init_CentOS.sh` delete the following content:

`````` bash
if [ ! -e "`which htop`" ];then
    cd src
    src_url=http://hisham.hm/htop/releases/1.0.3/htop-1.0.3.tar.gz && Download_src
    tar xzf htop-1.0.3.tar.gz
    cd htop-1.0.3
    ./configure
    make && make install
    cd ../../
fi```
``````

**Comment by oneinstack** [comment]
Network problems, you can use this link to download
Link:http://mirrors.linuxeye.com/oneinstack-full.tar.gz
